version: '3.8'
services:
  redis:
    image: redis:7
    container_name: fitmatch-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  mongo:
    image: mongo:latest
    container_name: fitmatch-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: fitmatch
    volumes:
      - mongo_data:/data/db

volumes:
  redis_data:
  mongo_data: 